### ISSUE TITLE
Role of Flink is not clear in README 

### ISSUE THREAD

**Issue by cagri387** [pinpoint-apm/pinpoint-docker#110]
It says: "The Pinpoint-Flink is necessary to use 'Application Inspector' feature." **but link provided is not working**. So there is no clue about role of pinpoint-flink in readme section.

Flink section in readMe: https://github.com/pinpoint-apm/pinpoint-docker#flink-configuration-optional

**Comment by ga-ram** [comment]
Broken links are now updated!
