### ISSUE TITLE
 pull access denied for pinpointdocker/pinpoint-flink

### ISSUE THREAD

**Issue by samuelgxc** [pinpoint-apm/pinpoint-docker#112]
[root@ansiblemaster pinpoint-docker-2.2.2]# docker-compose pull
Pulling pinpoint-mysql (pinpointdocker/pinpoint-mysql:2.2.2)...
2.2.2: Pulling from pinpointdocker/pinpoint-mysql
Digest: sha256:98254030405a0e922435a557ce6c5c4f017381e7ff5d29accb09250b56641427
Status: Image is up to date for pinpointdocker/pinpoint-mysql:2.2.2
Pulling zoo1 (zookeeper:3.4)...
3.4: Pulling from library/zookeeper
Digest: sha256:3882d9493d387ba77b7b69e2a031b9396477ec29483d51ceaed645c1389182e5
Status: Image is up to date for zookeeper:3.4
Pulling pinpoint-hbase (pinpointdocker/pinpoint-hbase:2.2.2)...
2.2.2: Pulling from pinpointdocker/pinpoint-hbase
Digest: sha256:444ece9391c58eb44eac145470d6157e67251a58d676fa2bb2e719188641b061
Status: Image is up to date for pinpointdocker/pinpoint-hbase:2.2.2
Pulling pinpoint-collector (pinpointdocker/pinpoint-collector:2.2.2)...
2.2.2: Pulling from pinpointdocker/pinpoint-collector
Digest: sha256:203b1c999c2eba1fe03087c971bdf8fa5f99745e2fd28936b90a8a4ecb2cc2cd
Status: Image is up to date for pinpointdocker/pinpoint-collector:2.2.2
Pulling pinpoint-agent (pinpointdocker/pinpoint-agent:2.2.2)...
2.2.2: Pulling from pinpointdocker/pinpoint-agent
Digest: sha256:33d74c34fb51b81fb21e74859ea6d8d80dde663e24be3ad9a68b7d98a5ba5f78
Status: Image is up to date for pinpointdocker/pinpoint-agent:2.2.2
Pulling pinpoint-quickstart (pinpointdocker/pinpoint-quickstart:latest)...
latest: Pulling from pinpointdocker/pinpoint-quickstart
Digest: sha256:3a241f64d8fa17bf55b6da01e53cc5ac746ab1a2c0e4d48195e78de3cce15052
Status: Image is up to date for pinpointdocker/pinpoint-quickstart:latest
Pulling pinpoint-web (pinpointdocker/pinpoint-web:2.2.2)...
2.2.2: Pulling from pinpointdocker/pinpoint-web
Digest: sha256:75be6fd9246fb4abed471327823c2ea1703fa565a6c97433953d6335377d4426
Status: Image is up to date for pinpointdocker/pinpoint-web:2.2.2
Pulling zoo2 (zookeeper:3.4)...
3.4: Pulling from library/zookeeper
Digest: sha256:3882d9493d387ba77b7b69e2a031b9396477ec29483d51ceaed645c1389182e5
Status: Image is up to date for zookeeper:3.4
Pulling zoo3 (zookeeper:3.4)...
3.4: Pulling from library/zookeeper
Digest: sha256:3882d9493d387ba77b7b69e2a031b9396477ec29483d51ceaed645c1389182e5
Status: Image is up to date for zookeeper:3.4
Pulling jobmanager (pinpointdocker/pinpoint-flink:2.2.2)...
ERROR: pull access denied for pinpointdocker/pinpoint-flink, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by ran222** [comment]
ERROR: for jobmanager  repository docker.io/pinpointdocker/pinpoint-flink not found: does not exist or no pull access

ERROR: for taskmanager  repository docker.io/pinpointdocker/pinpoint-flink not found: does not exist or no pull access
ERROR: repository docker.io/pinpointdocker/pinpoint-flink not found: does not exist or no pull access

**Comment by ga-ram** [comment]
pinpoint-flink docker hub repository was not there for some time (has been deleted for some unknown reason?) and now it is back up again from 2.3.1.

It seems like it doesn't have any problem pulling pinpoint-flink now.

**Comment by wzhuan520** [comment]
* Error response from daemon: pull access denied for pinpoint-flink-flink, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
