### ISSUE TITLE
pull access denied for pinpointdocker/pinpoint-flink, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by javaygq** [pinpoint-apm/pinpoint-docker#118]
[root@hostname pinpoint-docker]# docker-compose pull && docker-compose up -d
Pulling pinpoint-mysql      ... error
Pulling zoo1                ... done
Pulling pinpoint-hbase      ... error
Pulling pinpoint-collector  ... error
Pulling pinpoint-agent      ... error
Pulling pinpoint-quickstart ... done
Pulling pinpoint-web        ... error
Pulling zoo2                ... done
Pulling zoo3                ... done
Pulling jobmanager          ... error
Pulling taskmanager         ... error

ERROR: for pinpoint-collector  manifest for pinpointdocker/pinpoint-collector:2.3.0 not found: manifest unknown: manifest unknown

ERROR: for jobmanager  pull access denied for pinpointdocker/pinpoint-flink, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

ERROR: for pinpoint-mysql  manifest for pinpointdocker/pinpoint-mysql:2.3.0 not found: manifest unknown: manifest unknown

ERROR: for pinpoint-web  manifest for pinpointdocker/pinpoint-web:2.3.0 not found: manifest unknown: manifest unknown

ERROR: for taskmanager  pull access denied for pinpointdocker/pinpoint-flink, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

ERROR: for pinpoint-agent  manifest for pinpointdocker/pinpoint-agent:2.3.0 not found: manifest unknown: manifest unknown

ERROR: for pinpoint-hbase  manifest for pinpointdocker/pinpoint-hbase:2.3.0 not found: manifest unknown: manifest unknown
ERROR: pull access denied for pinpointdocker/pinpoint-flink, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

![image](https://user-images.githubusercontent.com/34884079/140682707-e30f4b74-74a7-42ad-b239-44d0ff78b867.png)

**Comment by ga-ram** [comment]
There were some problem auto-uploading v2.3.0 images to docker hub back then, so there were no images to pull with the command.

Now I have manually uploaded v2.3.0 images so it should work fine now.
