### ISSUE TITLE
ERROR: for jobmanager  repository docker.io/pinpointdocker/pinpoint-flink not found: does not exist or no pull access

### ISSUE THREAD

**Issue by javaygq** [pinpoint-apm/pinpoint-docker#119]
ERROR: for jobmanager  repository docker.io/pinpointdocker/pinpoint-flink not found: does not exist or no pull access

ERROR: for taskmanager  repository docker.io/pinpointdocker/pinpoint-flink not found: does not exist or no pull access
ERROR: repository docker.io/pinpointdocker/pinpoint-flink not found: does not exist or no pull access

_Originally posted by @ran222 in https://github.com/pinpoint-apm/pinpoint-docker/issues/112#issuecomment-924660983_

**Comment by javaygq** [comment]
![image](https://user-images.githubusercontent.com/34884079/140854689-367c97dd-fe49-441b-9fa2-4f0205b65e36.png)

**Comment by ga-ram** [comment]
pinpoint-flink docker hub repository was not there for some time (has been deleted for some unknown reason?) and now it is back up again from 2.3.1.

It seems like it doesn't have any problem pulling pinpoint-flink now.
