### ISSUE TITLE
When will version 2.3.2 be release？

### ISSUE THREAD

**Issue by art-kor** [pinpoint-apm/pinpoint-docker#122]
I need log4j security fix version of pinpoint
https://github.com/pinpoint-apm/pinpoint/releases/tag/v2.3.2

could you check 2.3.2 release time?

**Comment by Wooni-sj** [comment]
I also need this, can i know the schedule!? :)

**Comment by ga-ram** [comment]
I'm currently working on it.

**Comment by ga-ram** [comment]
it is now released and uploaded to docker hub

**Comment by art-kor** [comment]
@ga-ram 
thank you. Can you check the below?
https://github.com/pinpoint-apm/pinpoint-docker/issues/126
