### ISSUE TITLE
Could you include the pinpoint-batch container?

### ISSUE THREAD

**Issue by torreso** [pinpoint-apm/pinpoint-docker#130]
Could you include the pinpoint-batch container in the pinpoint-docker version as well?
Otherwise, it would be appreciated if you could provide a guide on how to use pinpoint-batch in your version of pinpoint-docker.

We haven't been able to use the alarm function since the upgrade.

**Comment by liucx1201** [comment]
What is your version? @torreso

**Comment by torreso** [comment]
I am using 2.3.2 version. @liucx1201

**Comment by liucx1201** [comment]
@ga-ram @emeroad help

**Comment by liucx1201** [comment]
> 我使用的是 2.3.2 版本。@liucx1201
Which docker-compose  version is available pinpoint-batch ？

**Comment by liucx1201** [comment]
Which docker-compose version is available pinpoint-batch ？@torreso

**Comment by torreso** [comment]
@liucx1201 

I am using docker-compose version 1.28.4, build cabd5cfb
