### ISSUE TITLE
HTTP parsing error occurs on removing application or agent on version 2.3.3

### ISSUE THREAD

**Issue by JunRadish** [pinpoint-apm/pinpoint-docker#132]
HTTP Parsing error occurs when I trying to remove application or agent on pinpoint's admin tab.
(FYI : We are using pinpoint-docker v.2.3.3 now.)

The below is error statements after I push the '**Remove**' button.
> Http failure during parsing for http://{Private_IP_Address}/admin/removeAgentId.pinpoint?applicationName=joker-dev&agentId=ip-10-1-100-100&password={PASSWORD}

When I Copy the above URL and paste it to the new tab, then i get the page with '**OK**' which remove the application or agent.

What should i check for fixing this issue.
Thanks.

**Comment by ga-ram** [comment]
This has been fixed with this PR (https://github.com/pinpoint-apm/pinpoint/pull/8416).
It seems like it hasn't been included in v2.3.3.

**Comment by JunRadish** [comment]
FYI who experiences "http parsing error" and hard to send an alert mail.

You can solve those 2 issues immediately by 
1. changing "pinpoint-flink-jobmanager"'s library jar file(pinpoint-flink-job.jar) with older version(for me, it was 2.2.2) and restart the container.
2. downgrade "pinpoint-web" to older version(for me it was 2.2.2)

After apply above two steps, we can use both functions normally.

I hope this can help your some of issues.
Thanks.
