### ISSUE TITLE
about pinpoint.config   version:pinpoint-docker:2.3.3

### ISSUE THREAD

**Issue by TengNo1** [pinpoint-apm/pinpoint-docker#134]
This is a question about pinpoint agent. Usually we use dockercompose and Env file can start pinpoint, but the sampling rate needs to be manually configured. Recently, when I considered deploying pinpoint on k8s, I wanted the agent to specify the sampling rate through the configuration file, but

I found that the new version still uses profiler_ SAMPLING_ Rate = ${profiler_sampling_rate} for configuration

I am configured as profiler_ SAMPLING_ Rate = 1 does not take effect because pinpoint Config has upgraded profiler sampling. counting. Sampling rate and profiler sampling. percent. Sample rate is used to configure the sampling rate. I hope I can configure these two items in dockercompose

**Comment by ga-ram** [comment]
You can now use new sampling configs in v2.4.1
