### ISSUE TITLE
Pinpoint 2.3.3: Alarm e-mails are not being send

### ISSUE THREAD

**Issue by amilhub** [pinpoint-apm/pinpoint-docker#136]
Hello,

Pinpoint : 2.3.3 
Pinpoint-agent: 2.3.3

The Pinpoint alarm e-mails are not  being send. 

I have correctly configured my SMTP details and i am able to fech (and resolve) to the mailserver port.
In previous Pinpoint versions (ex. 2.3.0) the mail alers are being sending correctly, I think the e-mail alerts stop working since the upgrade to 2.3.3 version.

Thanks in advance for help.

**Comment by ga-ram** [comment]
Alarm functions were part of pinpoint web until 2.2.0 and was separated into pinpoint batch at 2.2.1.
There hasn't been docker container for pinpoint batch until now but it will be updated for coming 2.4.0.
