### ISSUE TITLE
pinpoint  installation 404

### ISSUE THREAD

**Issue by liucx1201** [pinpoint-apm/pinpoint-docker#138]
pinpoint  docker version:2.4.0

installation 404

![instanllation404](https://user-images.githubusercontent.com/40434832/171373574-ca5dfc0c-6261-4938-8537-901511b3eec3.png)

http://125.209.240.10:10123/config/installation is 404

**Comment by liucx1201** [comment]
@[ga-ram](https://github.com/ga-ram) @emeroad  Local deployment is also 404，
Hopes it can be resolved

**Comment by liucx1201** [comment]
@ga-ram

**Comment by ga-ram** [comment]
@liucx1201 
Please use the installation link below until it is fixed: 
https://github.com/pinpoint-apm/pinpoint/releases/download/v2.4.0/pinpoint-agent-2.4.0.tar.gz
-javaagent:${pinpointPath}/pinpoint-bootstrap-2.4.0.jar

**Comment by liucx1201** [comment]
> @liucx1201 请使用下面的安装链接，直到它被修复： [https](https://github.com/pinpoint-apm/pinpoint/releases/download/v2.4.0/pinpoint-agent-2.4.0.tar.gz) ://github.com/pinpoint-apm/pinpoint/releases/download/v2.4.0/pinpoint-agent-2.4.0.tar.gz -javaagent:${pinpointPath }/pinpoint-bootstrap-2.4.0.jar

I is use docker-compose installation. How do I operate? @ga-ram

**Comment by liucx1201** [comment]
![pinpoint](https://user-images.githubusercontent.com/40434832/171534266-86f1c15e-01b7-418e-b7f3-b0f2b6fbc2df.png)

**Comment by ga-ram** [comment]
That installation page only provides links to the agent binary and nothing more.
It seems like you already have downloaded pinpoint-agent via docker hub.
Please refer to https://github.com/pinpoint-apm/pinpoint-docker/tree/master/pinpoint-agent-attach-example and see if you can attach pinpoint agent to your own application to start collecting information.

**Comment by ga-ram** [comment]
The issue originally mentioned is currently fixed in pinpoint and will be applied in next release
