### ISSUE TITLE
pinpoint-batch: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTraceDaoV2'

### ISSUE THREAD

**Issue by dxl727754275** [pinpoint-apm/pinpoint-docker#139]
docker versio:20.10.10
docker-compose version 1.29.2
linux centos7
command:
  git clone https://github.com/pinpoint-apm/pinpoint-docker.git
  cd pinpoint-docker
  docker-compose pull && docker-compose up -d

docker-compose logs -f  -->
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.p.t.TraceMetadataLoader          -- add PluginAnnotationKey:AnnotationKey{code=803, name='rocketmq.batch}
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.p.t.TraceMetadataLoader          -- add PluginAnnotationKey:AnnotationKey{code=804, name='rocketmq.send.status}
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.p.t.TraceMetadataLoader          -- add PluginAnnotationKey:AnnotationKey{code=805, name='rocketmq.broker.server}
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.p.t.TraceMetadataLoader          -- add PluginAnnotationKey:AnnotationKey{code=340, name='thread.name}
pinpoint-batch         | 07-06 02:45:57.057 [           main] WARN  ConfigServletWebServerApplicationContext -- Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTraceDaoV2': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: com/google/common/collect/ListMultimap
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.h.HbaseTemplate2                 -- HBaseTemplate2.destroy()
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.h.ConnectionFactoryBean          -- Hbase Connection destroy()
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  nectionManager$HConnectionImplementation -- Closing master protocol: MasterService
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  nectionManager$HConnectionImplementation -- Closing zookeeper sessionid=0x104aa810f4d0017
zoo3_1                 | 2022-07-06 02:45:57,292 [myid:3] - INFO  [ProcessThread(sid:3 cport:-1)::PrepRequestProcessor@487] - Processed session termination for sessionid: 0x104aa810f4d0017
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  o.a.h.h.s.o.a.z.ZooKeeper                -- Session: 0x104aa810f4d0017 closed
pinpoint-batch         | 07-06 02:45:57.057 [ain-EventThread] INFO  o.a.h.h.s.o.a.z.ClientCnxn               -- EventThread shut down for session: 0x104aa810f4d0017
zoo1_1                 | 2022-07-06 02:45:57,298 [myid:1] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1056] - Closed socket connection for client /192.168.80.10:58708 which had sessionid 0x104aa810f4d0017
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.z.h.HikariDataSource                   -- HikariPool-meta - Shutdown initiated...
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.z.h.HikariDataSource                   -- HikariPool-meta - Shutdown completed.
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.z.h.HikariDataSource                   -- HikariPool-dataSource - Shutdown initiated...
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.z.h.HikariDataSource                   -- HikariPool-dataSource - Shutdown completed.
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  o.a.c.c.StandardService                  -- Stopping service [Tomcat]
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   -- applicationEvent:ApplicationFailedEvent
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   -- PropertySource name configurationProperties
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   -- PropertySource name commandLineArgs
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   -- PropertySource name servletConfigInitParams
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   -- PropertySource name servletContextInitParams
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   -- PropertySource name systemProperties
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   -- PropertySource name systemEnvironment
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   -- PropertySource name random
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   -- PropertySource name Config resource 'file [/pinpoint/config/pinpoint-batch.properties]' via location '/pinpoint/config/pinpoint-batch.properties'
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   -- PropertySource name Config resource 'class path resource [application.yml]' via location 'optional:classpath:/'
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   -- PropertySource name PinpointProfileEnvironment 'pinpoint.profiles.active=release'
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   -- CompositePropertySource name BatchAppPropertySources-JDBC
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   --   class path resource [profiles/release/jdbc.properties]
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   --   class path resource [jdbc-root.properties]
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   -- CompositePropertySource name BatchAppPropertySources-HBase
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   --   class path resource [profiles/release/hbase.properties]
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   --   class path resource [hbase-root.properties]
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   -- CompositePropertySource name BatchAppPropertySources
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   --   class path resource [profiles/release/batch.properties]
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  c.n.p.c.s.e.EnvironmentLoggingListener   --   class path resource [batch-root.properties]
pinpoint-batch         | 07-06 02:45:57.057 [           main] INFO  ConditionEvaluationReportLoggingListener -- 
pinpoint-batch         | 
pinpoint-batch         | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
pinpoint-batch         | 07-06 02:45:57.057 [           main] ERROR o.s.b.SpringApplication                  -- Application run failed
pinpoint-batch         | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTraceDaoV2': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: com/google/common/collect/ListMultimap
pinpoint-batch         | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.3.20.jar!/:5.3.20]
pinpoint-batch         | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440) ~[spring-beans-5.3.20.jar!/:5.3.20]
pinpoint-batch         | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.3.20.jar!/:5.3.20]
pinpoint-batch         | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.20.jar!/:5.3.20]
pinpoint-batch         | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.20.jar!/:5.3.20]
pinpoint-batch         | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.20.jar!/:5.3.20]
pinpoint-batch         | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.20.jar!/:5.3.20]
pinpoint-batch         | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.20.jar!/:5.3.20]
pinpoint-batch         | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.20.jar!/:5.3.20]
pinpoint-batch         | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.20.jar!/:5.3.20]
pinpoint-batch         | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.20.jar!/:5.3.20]
pinpoint-batch         | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.20.jar!/:5.3.20]
pinpoint-batch         | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.12.jar!/:2.5.12]
pinpoint-batch         | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.5.12.jar!/:2.5.12]
pinpoint-batch         | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:448) [spring-boot-2.5.12.jar!/:2.5.12]
pinpoint-batch         | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) [spring-boot-2.5.12.jar!/:2.5.12]
pinpoint-batch         | 	at com.navercorp.pinpoint.common.server.starter.BasicStarter.start(BasicStarter.java:53) [pinpoint-commons-server-2.4.0.jar!/:2.4.0]
pinpoint-batch         | 	at com.navercorp.pinpoint.batch.BatchApp.main(BatchApp.java:46) [classes!/:2.4.0]
pinpoint-batch         | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
pinpoint-batch         | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
pinpoint-batch         | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
pinpoint-batch         | 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
pinpoint-batch         | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [pinpoint-batch.jar:2.4.0]
pinpoint-batch         | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [pinpoint-batch.jar:2.4.0]
pinpoint-batch         | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [pinpoint-batch.jar:2.4.0]
pinpoint-batch         | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [pinpoint-batch.jar:2.4.0]
pinpoint-batch         | Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/ListMultimap
pinpoint-batch         | 	at com.navercorp.pinpoint.web.dao.hbase.HbaseTraceDaoV2.setup(HbaseTraceDaoV2.java:109) ~[pinpoint-web-2.4.0.jar!/:2.4.0]
pinpoint-batch         | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
pinpoint-batch         | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
pinpoint-batch         | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
pinpoint-batch         | 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
pinpoint-batch         | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.20.jar!/:5.3.20]
pinpoint-batch         | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.3.20.jar!/:5.3.20]
pinpoint-batch         | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.3.20.jar!/:5.3.20]
pinpoint-batch         | 	... 25 more
pinpoint-batch         | Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ListMultimap
pinpoint-batch         | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:476) ~[?:?]
pinpoint-batch         | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
pinpoint-batch         | 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[pinpoint-batch.jar:2.4.0]
pinpoint-batch         | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
pinpoint-batch         | 	at com.navercorp.pinpoint.web.dao.hbase.HbaseTraceDaoV2.setup(HbaseTraceDaoV2.java:109) ~[pinpoint-web-2.4.0.jar!/:2.4.0]
pinpoint-batch         | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
pinpoint-batch         | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
pinpoint-batch         | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
pinpoint-batch         | 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
pinpoint-batch         | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.20.jar!/:5.3.20]
pinpoint-batch         | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.3.20.jar!/:5.3.20]
pinpoint-batch         | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.3.20.jar!/:5.3.20]
pinpoint-batch         | 	... 25 more
pinpoint-batch         | 07-06 02:45:57.423 ERROR BatchApp                            : [WebApp] could not launch app.
pinpoint-batch         | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTraceDaoV2': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: com/google/common/collect/ListMultimap
pinpoint-batch         | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
pinpoint-batch         | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
pinpoint-batch         | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
pinpoint-batch         | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
pinpoint-batch         | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
pinpoint-batch         | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
pinpoint-batch         | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
pinpoint-batch         | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
pinpoint-batch         | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
pinpoint-batch         | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
pinpoint-batch         | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
pinpoint-batch         | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
pinpoint-batch         | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
pinpoint-batch         | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
pinpoint-batch         | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:448)
pinpoint-batch         | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339)
pinpoint-batch         | 	at com.navercorp.pinpoint.common.server.starter.BasicStarter.start(BasicStarter.java:53)
pinpoint-batch         | 	at com.navercorp.pinpoint.batch.BatchApp.main(BatchApp.java:46)
pinpoint-batch         | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
pinpoint-batch         | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
pinpoint-batch         | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
pinpoint-batch         | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
pinpoint-batch         | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
pinpoint-batch         | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
pinpoint-batch         | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
pinpoint-batch         | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
pinpoint-batch         | Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/ListMultimap
pinpoint-batch         | 	at com.navercorp.pinpoint.web.dao.hbase.HbaseTraceDaoV2.setup(HbaseTraceDaoV2.java:109)
pinpoint-batch         | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
pinpoint-batch         | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
pinpoint-batch         | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
pinpoint-batch         | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
pinpoint-batch         | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
pinpoint-batch         | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
pinpoint-batch         | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
pinpoint-batch         | 	... 25 more
pinpoint-batch         | Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ListMultimap
pinpoint-batch         | 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
pinpoint-batch         | 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
pinpoint-batch         | 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
pinpoint-batch         | 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
pinpoint-batch         | 	... 33 more
pinpoint-batch exited with code 0

i need help ????

**Comment by ssmboxer** [comment]
Same problem here

**Comment by ga-ram** [comment]
I checked with the original batch jar image released for Pinpoint v2.4.0 and it has the same problem.
Just in case I tried clean+rebuilding the batch jar image but had no luck.

It seems like v2.4.0 batch itself has issues with finding com.google.common.collect.ListMultiMap.
Current master branch batch doesn't have this problem, so I assume it will be fixed in next release.

Meanwhile you can try adding -noverify option to `pinpoint-batch/build/scripts/start-batch.sh` like below and rebuild with `docker compose build` and run.

![Screen Shot 2022-07-20 at 11 42 50 AM](https://user-images.githubusercontent.com/3798235/179884624-6ed14322-37ed-492d-a5a5-58fd7eb1dff2.png)

It seems like it is working fine 🤷🏻‍♀️ but I'm not sure if it will have any other unexposed side effects, so above fix will not be added to the current branch.

**Comment by minwoo-jung** [comment]
I fixed this issue and pushed the code.

**Comment by yangxiuze** [comment]
Is it fixed in docker-pinpoint version 2.4?    There are still problems with the master branch.
07-22 06:45:11.011 [           main] ERROR o.s.b.SpringApplication                  -- Application run failed
pinpoint-batch         | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTraceDaoV2': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: com/google/common/collect/ListMultimap
pinpoint-batch         |        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.3.20.jar!/:5.3.20]
pinpoint-batch         |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440) ~[spring-beans-5.3.20.jar!/:5.3.20]

**Comment by ga-ram** [comment]
@yangxiuze It is not yet released for docker. I'll let you know when it is done.

**Comment by ga-ram** [comment]
v2.4.1 is now released and solves this problem.
