### ISSUE TITLE
Webhook alarm usage is not available for Pinpoint-Docker (Version: 2.4.1)

### ISSUE THREAD

**Issue by alptekinynk** [pinpoint-apm/pinpoint-docker#157]
https://pinpoint-apm.gitbook.io/pinpoint/documents/alarm

In the Pinpoint document page, it says that there are 3 different (sms, email, webhook) alarm options under the alarm usage title. But when pinpoint-docker is installed, there is no webhook setting as below. I want to use webhook alarm system with pinpoint-docker.

`# webhook config`
`webhook.enable=true`

**Comment by alptekinynk** [comment]
I solved the problem. The main problem is that the pinpoint document page is not enough. If you have installed pinpoint-docker:
contained in the Pinpoint-batch and Pinpoint-web containers.
into the p**inpoint/config/pinpoint-*.propeties file**
You need to add `webhook.enable=true`. The change made in pinpoint-batch is not enough, you should do the same in pinpoint-web. post change
You should do a reboot with `docker-compose restart`

**Comment by ga-ram** [comment]
it will be great if you can contribute to pinpoint document / docker compose yml 😄
