### ISSUE TITLE
Pinpoint webhook cannot be used with ms teams.

### ISSUE THREAD

**Issue by alptekinynk** [pinpoint-apm/pinpoint-docker#159]
I can't use the pinpoint webhook feature with ms-teams. The post request template sent by Pinpoint In webhook is not suitable for ms-teams and an error is returned as below.

`web.client.HttpClientErrorException$BadRequest: 400 : "Summary or Text is required."`

**Comment by ga-ram** [comment]
Then you need another server to translate pinpoint webhook into ms-teams form. 
Please check this repository in which receives pinpont webhook and sends slack webhook: https://github.com/doll6777/slack-receiver
