### ISSUE TITLE
请问，当我使用pinpoint-docker快速安装以后，我应该怎么样调用示例的quickapp，以及我应该如何配置agent？

### ISSUE THREAD

**Issue by fcy197778770** [pinpoint-apm/pinpoint-docker#187]
![image](https://github.com/pinpoint-apm/pinpoint-docker/assets/68221995/3ab47a34-4271-4598-ae40-22712ad1a5d5)
![image](https://github.com/pinpoint-apm/pinpoint-docker/assets/68221995/a22eb931-6a4c-4e43-8a9b-81afaaa334de)

**Comment by ga-ram** [comment]
Agent is already attached to quickapp in docker compose file.
You can access quickapp at localhost:8085 and pinpoint will trace the requests.
