### ISSUE TITLE
latest version has settings issues and doesnt work

### ISSUE THREAD

**Issue by RealZimboGuy** [pinpoint-apm/pinpoint-docker#190]
reverted to commit Release 2.5.3 and worked fine 

issues faced with latest version

        ERROR: The Compose file './docker-compose.yml' is invalid because:
        services.pinpoint-mysql.restart contains an invalid type, it should be a string
--- 
        /opt/pinpoint/pinpoint-docker# docker-compose pull && docker-compose up -d
        ERROR: build path /opt/pinpoint/pinpoint-docker/pinpoint-hbase either does not exist, is not accessible, or is not a valid URL.
---
        root@myserver:/opt/pinpoint/pinpoint-docker# docker-compose -f docker-compose.yml -f docker-compose-metric.yml build
        ERROR: build path /opt/pinpoint/pinpoint-docker/pinpoint-flink either does not exist, is not accessible, or is not a valid URL.
        root@myserver:/opt/pinpoint/pinpoint-docker# docker-compose -f docker-compose.yml -f docker-compose-metric.yml build
        ERROR: build path /opt/pinpoint/pinpoint-docker/pinpoint-hbase either does not exist, is not accessible, or is not a valid URL.
        root@myserver:/opt/pinpoint/pinpoint-docker# mkdir /opt/pinpoint/pinpoint-docker/pinpoint-hbase
        root@myserver:/opt/pinpoint/pinpoint-docker# docker-compose -f docker-compose.yml -f docker-compose-metric.yml build
        ERROR: build path /opt/pinpoint/pinpoint-docker/pinpoint-agent either does not exist, is not accessible, or is not a valid URL.
        root@myserver:/opt/pinpoint/pinpoint-docker# mkdir /opt/pinpoint/pinpoint-docker/pinpoint-agent
        root@myserver:/opt/pinpoint/pinpoint-docker# docker-compose -f docker-compose.yml -f docker-compose-metric.yml build
        ERROR: build path /opt/pinpoint/pinpoint-docker/pinpoint-flink either does not exist, is not accessible, or is not a valid URL.
        root@myserver:/opt/pinpoint/pinpoint-docker# mkdir /opt/pinpoint/pinpoint-docker/pinpoint-flink
        root@myserver:/opt/pinpoint/pinpoint-docker# docker-compose -f docker-compose.yml -f docker-compose-metric.yml build
        ERROR: build path /opt/pinpoint/pinpoint-docker/pinpoint-batch either does not exist, is not accessible, or is not a valid URL.
        root@myserver:/opt/pinpoint/pinpoint-docker# mkdir /opt/pinpoint/pinpoint-docker/pinpoint-batch
        root@myserver:/opt/pinpoint/pinpoint-docker# docker-compose -f docker-compose.yml -f docker-compose-metric.yml build
        ERROR: build path /opt/pinpoint/pinpoint-docker/pinpoint-collector either does not exist, is not accessible, or is not a valid URL.
        root@myserver:/opt/pinpoint/pinpoint-docker# mkdir /opt/pinpoint/pinpoint-docker/pinpoint-collector
        root@myserver:/opt/pinpoint/pinpoint-docker# docker-compose -f docker-compose.yml -f docker-compose-metric.yml build
        ERROR: build path /opt/pinpoint/pinpoint-docker/pinpoint-web either does not exist, is not accessible, or is not a valid URL.
        root@myserver:/opt/pinpoint/pinpoint-docker# mkdir /opt/pinpoint/pinpoint-docker/pinpoint-web
        root@myserver:/opt/pinpoint/pinpoint-docker# docker-compose -f docker-compose.yml -f docker-compose-metric.yml build
        zoo2 uses an image, skipping
        zoo1 uses an image, skipping
        redis uses an image, skipping
        pinpoint-mysql uses an image, skipping
        zoo3 uses an image, skipping
        pinot-zoo uses an image, skipping
        pinot-controller uses an image, skipping
        pinot-broker-0 uses an image, skipping
        pinot-server-0 uses an image, skipping
        pinpoint-kafka uses an image, skipping
        pinpoint-kafka-init uses an image, skipping
        pinot-init uses an image, skipping
        telegraf uses an image, skipping
        Building jobmanager
        ERROR: Cannot locate specified Dockerfile: Dockerfile

**Comment by ga-ram** [comment]
<img width="640" alt="Screenshot 2024-02-13 at 11 14 33 AM" src="https://github.com/pinpoint-apm/pinpoint-docker/assets/3798235/1d14fe4a-fbf4-4816-90b7-ba1bb4201365">

Would you try again with `services.pinpoint-mysql.restart: "no"`instead of current `services.pinpoint-mysql.restart: no` ?

Also, some directories are removed since the images will be built with maven plugins in https://github.com/pinpoint-apm/pinpoint project, so you don't need to `docker-compose build` to get metric images from now on. I will update compose files and the readme document accordingly.
