### ISSUE TITLE
URI statistics not showing data 

### ISSUE THREAD

**Issue by srinath6132** [pinpoint-apm/pinpoint-docker#204]
my application runing on prweb.war file and under postgresql database 
added below configuration not showing any data on Url  statistics my application runing on docker

Q do we need to add collector.stat.uri=true and config.show.urlStat=true  in .env file?

# Enable URI statistics
profiler.uri.stat.enable=true

# Tomcat specific configuration (if using Tomcat)
profiler.uri.stat.tomcat.enable=true
profiler.uri.stat.tomcat.useuserinput=false

# HTTP Client and Server monitoring
profiler.uri.stat.httpclient.enable=true
profiler.uri.stat.httpclient.useuserinput=false
profiler.uri.stat.httpserver.enable=true
profiler.uri.stat.httpserver.useuserinput=false

# JDBC Monitoring
profiler.jdbc.tracing.enable=true
profiler.jdbc.postgresql.enable=true
profiler.jdbc.maxsqlbindvalue.length=1024
profiler.jdbc.sqlcachesize=1024

Please suggest in this

**Comment by ga-ram** [comment]
Properties related to uri stat are enabled as default if you started up Pinpoint cluster with below command.
``` 
docker-compose -f docker-compose.yml -f docker-compose-metric.yml up -d
```

If you are using external property files for your environment, please refer to [our gitbook documents](https://pinpoint-apm.gitbook.io/pinpoint/documents/uri_statistics) to check if necessary properties are set correctly.
