### ISSUE TITLE
latest 버전을 받아서 설치 중 basicLogin을 적용하고자 하나 PIN POINT WEB의 pinpoint-web.prorperties 나 JAVA_OPTS 전달 방법을 찾을 수 없습니다.

### ISSUE THREAD

**Issue by jaewon-kim** [pinpoint-apm/pinpoint-docker#205]
latest(3.0.1) 버전을 checkout  받아서 확인하고 있으나 
docker-compose.yml 이나 .env에서 basicLogin을 적용하기 위한 
properties 수정 방법이나 JAVA_OPTS 를 전달 할 수 있는 방법을 찾지 못하여 도움을 요청합니다.

**Comment by ga-ram** [comment]
Currently [basicLogin does not properly work](https://github.com/pinpoint-apm/pinpoint/issues/11167) with the latest release (v3.0.0).
Please wait until **v3.0.1** release to use this function.
With **v3.0.1**, set `PINPOINT_MODULES_WEB_LOGIN` to basicLogin, and modify `WEB_SECURITY_AUTH_USER`, `WEB_SECURITY_AUTH_ADMIN`, `WEB_SECURITY_AUTH_JWT_SECRET_KEY` to your preferences in .env file.

With **v2.5.x** images, add `basicLogin` profile to `SPRING_PROFILES` in .env file to use basic login. 
i.e.) 
```
PINPOINT_VERSION=2.5.4
SPRING_PROFILES=release,basicLogin
```
You can modify `WEB_SECURITY_AUTH_USER`, `WEB_SECURITY_AUTH_ADMIN`, `WEB_SECURITY_AUTH_JWT_SECRET_KEY` as well to change user, admin, JWT secret key properties

**Comment by jaewon-kim** [comment]
@ga-ram Thank you , I'll wait next release.
