### ISSUE TITLE
When will Docker version update 3.0

### ISSUE THREAD

**Issue by liujiangxu** [pinpoint-apm/pinpoint-docker#226]
When will Docker version update 3.0

**Comment by liujiangxu** [comment]
x

**Comment by liujiangxu** [comment]
x

**Comment by kojandy** [comment]
You can pull images from Docker Hub up to version 3.0.1 currently.

https://hub.docker.com/r/pinpointdocker

**Comment by liujiangxu** [comment]
@kojandy thanks
