### ISSUE TITLE
Inquire about how to set up email when configuring with docker.

### ISSUE THREAD

**Issue by moondal** [pinpoint-apm/pinpoint-docker#227]
Inquire about how to set up email when configuring with docker.
Hello, 

I'm working on it
https://pinpoint-apm.gitbook.io/pinpoint/documents/alarm#id-2
We are conducting an email configuration test according to the page here.
2.1 Configuration & Implementation in pinpoint-batch

At this stage
pinpoint-docker-2.5.3/pinpoint-batch/build/config/pinpoint-batch.properties
I have added the file as below.

pinpoint.url= #pinpoint-web server url
alarm.mail.server.url= #smtp server address
alarm.mail.server.port= #smtp server port
alarm.mail.server.username= #username for smtp server authentication
alarm.mail.server.password= #password for smtp server authentication
alarm.mail.sender.address= #sender's email address

2.1.2) Configuring MYSQL
 Here 
Set up a MYSQL server and configure connection information in jdbc-root.properties file.

Copy
jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:13306/pinpoint
jdbc.username=admin
jdbc.password=admin

It says that, but I would like to ask you how to configure it in the docker environment.

And 
pinpoint.url= #pinpoint-web server url
alarm.mail.server.url= #smtp server address
alarm.mail.server.port= #smtp server port
alarm.mail.server.username= #username for smtp server authentication
alarm.mail.server.password= #password for smtp server authentication
alarm.mail.sender.address= #sender's email address
The mail server I use does not have a user or password, so I would like to ask if I should not use the variable.

Thank you.

**Comment by minwoo-jung** [comment]
Hi @moondal 
If you don't need username and password, you don't need to set them.

**Comment by moondal** [comment]
@minwoo-jung 
Thank you for your quick reply.
pinpoint-docker-2.5.3/pinpoint-batch/build/config/pinpoint-batch.properties
Can I know where to set this file in pinpoint-batch Docker?

**Comment by kojandy** [comment]
Hello, @moondal.

You can add desired properties to `.env`.
Please refer to the two files below.
https://github.com/pinpoint-apm/pinpoint-docker/blob/master/.env#L87-L97
https://github.com/pinpoint-apm/pinpoint-docker/blob/master/docker-compose.yml#L185-L215
