### ISSUE TITLE
JAVA_OPTS environment variable seems to be ignored.

### ISSUE THREAD

**Issue by yblee84** [pinpoint-apm/pinpoint-docker#89]
Hi. pinpoint-web docker use JAVA_OPTS environment for spring.profiles.active. but that variable seem to be ignored.
So pinpoint-web profile is always release only. (i expect that profile is release,batch). I think JAVA_OPTS should be replaced _JAVA_OPTIONS.

**Comment by RoySRose** [comment]
@yblee84 

You're right :) There is a typo in docker-compose and two unnecessary lines in the docker file.

Would like to make a PR for it?

**Comment by RoySRose** [comment]
fixed
